Add a command to install the executable directly from the source repository
hansmi/wp2reg-luxws pull request #42
Opened 2023-05-13 08:41 UTC by ppetr

Also some minor fixes/improvements of links.

2023-05-14 22:12 UTC, hansmi requested changes
Got a few comments. Please let me know if I should take care of them.

2023-05-15 08:10 UTC, ppetr commented on wp2reg-luxws-exporter.service
> +; The fields below are optional, but strongly recommended: The service is put
Mostly I agree on this and I'll update the file as you suggest. The only case where I'd argue is the `DynamicUser`: This significantly increases security of the service, and at the same time it's something that isn't a purely policy decision, because it might need other settings depending on which file a service accesses etc. So at least I'd keep this as a comment that can be uncommented by users.

2023-05-15 08:10 UTC, ppetr commented on wp2reg-luxws-exporter.service
ACK

2023-05-15 08:10 UTC, ppetr commented on README.md
> +With [Go 1.16][go1.16] or later the following command installs `luxws-exporter`
ACK

2023-05-15 20:35 UTC, hansmi commented on wp2reg-luxws-exporter.service
> +; The fields below are optional, but strongly recommended: The service is put
I'd argue that compiling and installing binaries as root (and likely talking to remote services for fetching modules) is considerably worse than anything `DynamicUser` could ever provide. ;-)

On a serious note I'm fine with leaving `DynamicUser` in there. If you want I can also follow-up to add the systemd unit to the pre-built packages.

2023-05-22 09:48 UTC, ppetr commented on wp2reg-luxws-exporter.service
> +ExecStart=/usr/local/sbin/luxws-exporter --controller.address=192.168.0.1:8214 --controller.address.http=192.168.0.1:80 --controller.language=cz --web.listen-address=localhost:9101
Done. I was wondering if it'd make sense to split it into multiple environment variables, but for the time being I kept it the same way as your example.

2023-05-22 09:52 UTC, ppetr commented on wp2reg-luxws-exporter.service
> +; The fields below are optional, but strongly recommended: The service is put
Point taken :sweat_smile:

2023-05-22 09:52 UTC, ppetr commented on wp2reg-luxws-exporter.service
Done.

2023-05-22 09:52 UTC, ppetr commented on README.md
> +With [Go 1.16][go1.16] or later the following command installs `luxws-exporter`
Done.

2023-05-22 09:54 UTC, ppetr commented
I addressed your comments. I created a new commit for them, since I'm using mercurial-git and it breaks the repo when attempting to rewrite history, so feel free to squash them into a single one.

2023-05-24 22:02 UTC, hansmi approved these changes
Looks good to me. I'll squash the commits locally.

2023-05-24 22:03 UTC, merged